export interface Empresa {
  name?:string,
  descricao?: string,
  cnpj?: string ,
  site?: string,
  instagram?: string,
  telefone?: string,
  streinstagramet?: string,
  cep?:string,
  logradouro?: string,
  complemento?:string,
  bairro?: string,
  localidade?: string,
  numero?: string,
  uf?: string ,
  ibge?: string,
  gia?: string,
  ddd?: string,
  siafi?: string,
  imagem?:string,
  imagemview?: string,
  email?: string ,
  extension?: string,
  fantasia?: string,
}
